<a href="https://colab.research.google.com/github/Adriansyah14/User-Segmentation/blob/main/Project_User_Segmentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pertanyaan atau permasalahan**

*   Bagaimana pengelompokkan pengguna berdasarkan RFM segmentation?

**Variabel pada dataset**



1.   order_id : kode unik pemesanan
2.   Product_code : kode pada produk
3.   product_name : nama produk
4.   quantity : jumlah produk pada tiap pesanan
5.   order_date : tanggal pemesanan
6.   price : harga produk
7.   customer_id : kode unik pelanggan

# Install dan impor packages

Install dan impor package-packages yang akan digunakan

In [ ]:
# pip install pandas
# pip install numpy
# pip install datetime

import datetime as dt
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/Adriansyah14/User-Segmentation/refs/heads/main/Salinan_Online_Retail_Data.csv")
df

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461773 entries, 0 to 461772
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      461773 non-null  object
 1   product_code  461773 non-null  object
 2   product_name  459055 non-null  object
 3   quantity      461773 non-null  int64
 4   order_date    461773 non-null  object
 5   price         461773 non-null  float64
 6   customer_id   360853 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 24.7+ MB

# Cleaning Data

In [9]:
# tampilkan missing value
df.isnull().sum()

order_id             0
product_code         0
product_name      2718
quantity             0
order_date           0
price                0
customer_id     100920
dtype: int64

In [10]:
# buat salinan dataset
df_clean = df.copy()

In [11]:
# hapus/drop semua baris yang tidak memiliki product_name
df_clean = df_clean[~df_clean["product_name"].isnull()]

In [12]:
# hapus/drop semua baris yang tidak memiliki customer_id
df_clean = df_clean[~df_clean["customer_id"].isna()]

In [13]:
df_clean.isnull().sum()

order_id        0
product_code    0
product_name    0
quantity        0
order_date      0
price           0
customer_id     0
dtype: int64

In [15]:
# membuat kolom date
df_clean["date"] = pd.to_datetime(df_clean["order_date"]).dt.date.astype("datetime64[ns]")

In [16]:
# ubah product_name jadi huruf kecil
df_clean["product_name"] = df_clean["product_name"].str.lower()

In [17]:
# hapus semua baris dengan prdoct_code atau product_name_test
df_clean = df_clean[(~df_clean['product_code'].str.lower().str.contains('test')) |
                    (~df_clean['product_name'].str.contains('test '))]

In [18]:
# buat kolom baru yaitu order_status dengan nilai "cancelled" jika pada order_id diawali huru 'C' dan "delivered" jika order_id tidak terdapat awalan huruf 'C'
df_clean['order_status'] = np.where(df_clean['order_id'].str[:1]=='C', 'cancelled', 'delivered')

In [19]:
# mengubah nilai quantity yg negatif ke positif karena nilai negatif menandakan order cancelled
df_clean['quantity'] = df_clean['quantity'].abs()

In [20]:
# hapus baris pada price bernilai negatif
df_clean = df_clean[df_clean['price']>0]

In [21]:
# membuat kolom amount, yaitu perkalian antara quantity dan price
df_clean['amount'] = df_clean['quantity'] * df_clean['price']

In [22]:
# mengganti product_name dari product_code yang memiliki beberapa product_name dengan salah satu product_name-nya yang paling sering muncul
most_freq_product_name = df_clean.groupby(['product_code','product_name'], as_index=False).agg(order_cnt=('order_id','nunique')).sort_values(['product_code','order_cnt'], ascending=[True,False])
most_freq_product_name['rank'] = most_freq_product_name.groupby('product_code')['order_cnt'].rank(method='first', ascending=False)
most_freq_product_name = most_freq_product_name[most_freq_product_name['rank']==1].drop(columns=['order_cnt','rank'])
df_clean = df_clean.merge(most_freq_product_name.rename(columns={'product_name':'most_freq_product_name'}), how='left', on='product_code')
df_clean['product_name'] = df_clean['most_freq_product_name']
df_clean = df_clean.drop(columns='most_freq_product_name')

In [25]:
# mengkonversi tipe data customer_id menjadi string
df_clean['customer_id'] = df_clean['customer_id'].astype(str)

In [24]:
# menghapus outlier
from scipy import stats
df_clean = df_clean[(np.abs(stats.zscore(df_clean[['quantity','amount']]))<3).all(axis=1)]
df_clean = df_clean.reset_index(drop=True)
df_clean

,order_id,product_code,product_name,quantity,order_date,price,customer_id,date,order_status,amount
0,C493411,21539,red retrospot butter dish,1,2010-01-04 09:43:00,4.25,14590.0,2010-01-04,cancelled,4.25
1,493414,21844,red retrospot mug,36,2010-01-04 10:28:00,2.55,14590.0,2010-01-04,delivered,91.80
2,493414,21533,retro spot large milk jug,12,2010-01-04 10:28:00,4.25,14590.0,2010-01-04,delivered,51.00
3,493414,37508,new england ceramic cake server,2,2010-01-04 10:28:00,2.55,14590.0,2010-01-04,delivered,5.10
4,493414,35001G,hand open shape gold,2,2010-01-04 10:28:00,4.25,14590.0,2010-01-04,delivered,8.50
...,...,...,...,...,...,...,...,...,...,...
358464,539988,84380,set of 3 butterfly cookie cutters,1,2010-12-23 16:06:00,1.25,18116.0,2010-12-23,delivered,1.25
358465,539988,84849D,hot baths soap holder,1,2010-12-23 16:06:00,1.69,18116.0,2010-12-23,delivered,1.69
358466,539988,84849B,fairy soap soap holder,1,2010-12-23 16:06:00,1.69,18116.0,2010-12-23,delivered,1.69
358467,539988,22854,cream sweetheart egg holder,2,2010-12-23 16:06:00,4.95,18116.0,2010-12-23,delivered,9.90
358468,539988,47559B,tea time oven glove,2,2010-12-23 16:06:00,1.25,18116.0,2010-12-23,delivered,2.50

In [26]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358469 entries, 0 to 358468
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      358469 non-null  object
 1   product_code  358469 non-null  object
 2   product_name  358469 non-null  object
 3   quantity      358469 non-null  int64
 4   order_date    358469 non-null  object
 5   price         358469 non-null  float64
 6   customer_id   358469 non-null  object
 7   date          358469 non-null  datetime64[ns]
 8   order_status  358469 non-null  object
 9   amount        358469 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 27.3+ MB

# Membuat RFM segmentation

## Agregat data transaksi ke bentuk summary total transaksi (order), total nilai order (order value), tanggal order terakhir dari setiap pengguna

In [27]:
df_user = df_clean.groupby(['customer_id'], as_index=False).agg(order_cnt=('order_id','nunique'), total_order_value=('amount','sum'), max_order_date=('date','max'))
df_user

     customer_id  order_cnt  total_order_value max_order_date
0        12346.0          5             602.40     2010-10-04
1        12608.0          1             415.79     2010-10-31
2        12745.0          2             723.85     2010-08-10
3        12746.0          2             266.35     2010-06-30
4        12747.0         19            4094.79     2010-12-13
...          ...        ...                ...            ...
3884     18283.0          6             641.77     2010-11-22
3885     18284.0          2             486.68     2010-10-06
3886     18285.0          1             427.00     2010-02-17
3887     18286.0          2             941.48     2010-08-20
3888     18287.0          4            2345.71     2010-11-22

[3889 rows x 4 columns]

## Buat kolom jumlah hari terakhir order

In [29]:
today = df_clean['date'].max()

In [30]:
df_user['days_since_last_order'] = (today - df_user['max_order_date']).dt.days
df_user

,customer_id,order_cnt,total_order_value,max_order_date,days_since_last_order
0,12346.0,5,602.40,2010-10-04,80
1,12608.0,1,415.79,2010-10-31,53
2,12745.0,2,723.85,2010-08-10,135
3,12746.0,2,266.35,2010-06-30,176
4,12747.0,19,4094.79,2010-12-13,10
...,...,...,...,...,...
3884,18283.0,6,641.77,2010-11-22,31
3885,18284.0,2,486.68,2010-10-06,78
3886,18285.0,1,427.00,2010-02-17,309
3887,18286.0,2,941.48,2010-08-20,125
3888,18287.0,4,2345.71,2010-11-22,31

In [31]:
df_user.describe()

,order_cnt,total_order_value,max_order_date,days_since_last_order
count,3889.000000,3889.000000,3889,3889.000000
mean,5.128568,1544.623084,2010-09-23 04:46:57.793777664,90.800720
min,1.000000,1.250000,2010-01-05 00:00:00,0.000000
25%,1.000000,296.360000,2010-08-19 00:00:00,25.000000
50%,3.000000,648.200000,2010-10-26 00:00:00,58.000000
75%,6.000000,1585.940000,2010-11-28 00:00:00,126.000000
max,163.000000,71970.390000,2010-12-23 00:00:00,352.000000
std,8.499330,3434.816315,NaN,88.873286

## Buat binning dari jumlah hari sejak order terakhir, yang terdiri dari 5 bins dengan batas min, P20, P40, P60, P80, max dan beri label 1-5 dari nilai bin tertinggi ke terendah ssebagai skor recency

In [33]:
df_user['recency_score'] = pd.cut(df_user['days_since_last_order'],
                                  bins=[df_user['days_since_last_order'].min(),
                                        np.percentile(df_user['days_since_last_order'], 20),
                                        np.percentile(df_user['days_since_last_order'], 40),
                                        np.percentile(df_user['days_since_last_order'], 60),
                                        np.percentile(df_user['days_since_last_order'], 80),
                                        df_user['days_since_last_order'].max()],
                                  labels=[5, 4, 3, 2, 1],
                                  include_lowest=True).astype(int)
df_user

,customer_id,order_cnt,total_order_value,max_order_date,days_since_last_order,recency_score
0,12346.0,5,602.40,2010-10-04,80,2
1,12608.0,1,415.79,2010-10-31,53,3
2,12745.0,2,723.85,2010-08-10,135,2
3,12746.0,2,266.35,2010-06-30,176,1
4,12747.0,19,4094.79,2010-12-13,10,5
...,...,...,...,...,...,...
3884,18283.0,6,641.77,2010-11-22,31,4
3885,18284.0,2,486.68,2010-10-06,78,2
3886,18285.0,1,427.00,2010-02-17,309,1
3887,18286.0,2,941.48,2010-08-20,125,2
3888,18287.0,4,2345.71,2010-11-22,31,4

In [34]:
# cek df_user setelah penambahan kolom
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3889 non-null   object
 1   order_cnt              3889 non-null   int64
 2   total_order_value      3889 non-null   float64
 3   max_order_date         3889 non-null   datetime64[ns]
 4   days_since_last_order  3889 non-null   int64
 5   recency_score          3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 182.4+ KB

## Buat binning dari total transaksi (order) yang terdiri dari 5 bins dengan batas-batasnya merupakan min, P20, P40, P60, P80, max dan beri label 1-5 dari bin terendah ke tertinggi sebagai skor frequency

In [37]:
df_user['frequency_score'] = pd.cut(df_user['order_cnt'],
                                    bins=[0,
                                          np.percentile(df_user['order_cnt'], 20),
                                          np.percentile(df_user['order_cnt'], 40),
                                          np.percentile(df_user['order_cnt'], 60),
                                          np.percentile(df_user['order_cnt'], 80),
                                          df_user['order_cnt'].max()],
                                    labels=[1, 2, 3, 4, 5],
                                    include_lowest=True).astype(int)

In [38]:
df_user

,customer_id,order_cnt,total_order_value,max_order_date,days_since_last_order,recency_score,frequency_score
0,12346.0,5,602.40,2010-10-04,80,2,4
1,12608.0,1,415.79,2010-10-31,53,3,1
2,12745.0,2,723.85,2010-08-10,135,2,2
3,12746.0,2,266.35,2010-06-30,176,1,2
4,12747.0,19,4094.79,2010-12-13,10,5,5
...,...,...,...,...,...,...,...
3884,18283.0,6,641.77,2010-11-22,31,4,4
3885,18284.0,2,486.68,2010-10-06,78,2,2
3886,18285.0,1,427.00,2010-02-17,309,1,1
3887,18286.0,2,941.48,2010-08-20,125,2,2
3888,18287.0,4,2345.71,2010-11-22,31,4,3

In [39]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3889 non-null   object
 1   order_cnt              3889 non-null   int64
 2   total_order_value      3889 non-null   float64
 3   max_order_date         3889 non-null   datetime64[ns]
 4   days_since_last_order  3889 non-null   int64
 5   recency_score          3889 non-null   int64
 6   frequency_score        3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(4), object(1)
memory usage: 212.8+ KB

## Buat binning dari total nilai order (order value) yang terdiri dari 5 bins dengan batas-batasnya merupakan min, P20, P40, P60, P80, max dan beri label 1 sampai 5 dari bin terendah ke tertinggi sebagai skor monetary

In [40]:
df_user['monetary_score'] = pd.cut(df_user['total_order_value'],
                                   bins=[df_user['total_order_value'].min(),
                                         np.percentile(df_user['total_order_value'], 20),
                                         np.percentile(df_user['total_order_value'], 40),
                                         np.percentile(df_user['total_order_value'], 60),
                                         np.percentile(df_user['total_order_value'], 80),
                                         df_user['total_order_value'].max()],
                                   labels=[1, 2, 3, 4, 5],
                                   include_lowest=True).astype(int)
df_user

,customer_id,order_cnt,total_order_value,max_order_date,days_since_last_order,recency_score,frequency_score,monetary_score
0,12346.0,5,602.40,2010-10-04,80,2,4,3
1,12608.0,1,415.79,2010-10-31,53,3,1,2
2,12745.0,2,723.85,2010-08-10,135,2,2,3
3,12746.0,2,266.35,2010-06-30,176,1,2,2
4,12747.0,19,4094.79,2010-12-13,10,5,5,5
...,...,...,...,...,...,...,...,...
3884,18283.0,6,641.77,2010-11-22,31,4,4,3
3885,18284.0,2,486.68,2010-10-06,78,2,2,3
3886,18285.0,1,427.00,2010-02-17,309,1,1,2
3887,18286.0,2,941.48,2010-08-20,125,2,2,4
3888,18287.0,4,2345.71,2010-11-22,31,4,3,5

In [41]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3889 non-null   object
 1   order_cnt              3889 non-null   int64
 2   total_order_value      3889 non-null   float64
 3   max_order_date         3889 non-null   datetime64[ns]
 4   days_since_last_order  3889 non-null   int64
 5   recency_score          3889 non-null   int64
 6   frequency_score        3889 non-null   int64
 7   monetary_score         3889 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(5), object(1)
memory usage: 243.2+ KB

## Buat kolom baru dengan nama 'segment' berdasarkan 'recency_score' dan 'frequency_score'

In [42]:
df_user['segment'] = np.select(
    [(df_user['recency_score']==5) & (df_user['frequency_score']>=4),
     (df_user['recency_score'].between(3, 4)) & (df_user['frequency_score']>=4),
     (df_user['recency_score']>=4) & (df_user['frequency_score'].between(2, 3)),
     (df_user['recency_score']<=2) & (df_user['frequency_score']==5),
     (df_user['recency_score']==3) & (df_user['frequency_score']==3),
     (df_user['recency_score']==5) & (df_user['frequency_score']==1),
     (df_user['recency_score']==4) & (df_user['frequency_score']==1),
     (df_user['recency_score']<=2) & (df_user['frequency_score'].between(3, 4)),
     (df_user['recency_score']==3) & (df_user['frequency_score']<=2),
     (df_user['recency_score']<=2) & (df_user['frequency_score']<=2)],
    ['01-Champion', '02-Loyal Customers', '03-Potential Loyalists', "04-Can't Lose Them", '05-Need Attention',
     '06-New Customers', '07-Promising', '08-At Risk', '09-About to Sleep', '10-Hibernating']
)
df_user

,customer_id,order_cnt,total_order_value,max_order_date,days_since_last_order,recency_score,frequency_score,monetary_score,segment
0,12346.0,5,602.40,2010-10-04,80,2,4,3,08-At Risk
1,12608.0,1,415.79,2010-10-31,53,3,1,2,09-About to Sleep
2,12745.0,2,723.85,2010-08-10,135,2,2,3,10-Hibernating
3,12746.0,2,266.35,2010-06-30,176,1,2,2,10-Hibernating
4,12747.0,19,4094.79,2010-12-13,10,5,5,5,01-Champion
...,...,...,...,...,...,...,...,...,...
3884,18283.0,6,641.77,2010-11-22,31,4,4,3,02-Loyal Customers
3885,18284.0,2,486.68,2010-10-06,78,2,2,3,10-Hibernating
3886,18285.0,1,427.00,2010-02-17,309,1,1,2,10-Hibernating
3887,18286.0,2,941.48,2010-08-20,125,2,2,4,10-Hibernating
3888,18287.0,4,2345.71,2010-11-22,31,4,3,5,03-Potential Loyalists

In [43]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3889 entries, 0 to 3888
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3889 non-null   object
 1   order_cnt              3889 non-null   int64
 2   total_order_value      3889 non-null   float64
 3   max_order_date         3889 non-null   datetime64[ns]
 4   days_since_last_order  3889 non-null   int64
 5   recency_score          3889 non-null   int64
 6   frequency_score        3889 non-null   int64
 7   monetary_score         3889 non-null   int64
 8   segment                3889 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 273.6+ KB

## Tampilkan summary RMF segmentation

In [45]:
summary = pd.pivot_table(df_user, index='segment',
               values=['customer_id','days_since_last_order','order_cnt','total_order_value'],
               aggfunc={'customer_id': pd.Series.nunique,
                        'days_since_last_order': [np.mean, np.median],
                        'order_cnt': [np.mean, np.median],
                        'total_order_value': [np.mean, np.median]})
summary['pct_unique'] = (summary['customer_id'] / summary['customer_id'].sum() * 100).round(1)
summary

<ipython-input-45-7c563304d7a7>:1: FutureWarning: The provided callable <function mean at 0x7b30571f5000> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  summary = pd.pivot_table(df_user, index='segment',
<ipython-input-45-7c563304d7a7>:1: FutureWarning: The provided callable <function median at 0x7b3054420700> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  summary = pd.pivot_table(df_user, index='segment',

                       customer_id days_since_last_order         order_cnt  \
                           nunique                  mean median       mean
segment
01-Champion                    550             10.618182    9.5  15.467273
02-Loyal Customers             546             40.864469   37.0   8.767399
03-Potential Loyalists         523             23.573614   24.0   2.829828
04-Can't Lose Them              64            121.984375  112.5  11.375000
05-Need Attention              176             58.613636   59.0   3.397727
06-New Customers                50             14.220000   16.0   1.000000
07-Promising                   142             32.760563   34.0   1.000000
08-At Risk                     426            140.455399  120.0   4.136150
09-About to Sleep              352             58.735795   58.0   1.417614
10-Hibernating                1060            196.837736  199.0   1.313208

                              total_order_value           pct_unique
                       median              mean    median
segment
01-Champion              10.0       5003.674245  2775.525       14.1
02-Loyal Customers        7.0       2622.817826  1946.850       14.0
03-Potential Loyalists    3.0        766.769828   622.070       13.4
04-Can't Lose Them        9.5       2839.948125  2268.405        1.6
05-Need Attention         3.0        989.232676   826.370        4.5
06-New Customers          1.0        244.689000   193.675        1.3
07-Promising              1.0        287.800282   238.440        3.7
08-At Risk                4.0       1153.825683   875.430       11.0
09-About to Sleep         1.0        448.229688   334.755        9.1
10-Hibernating            1.0        343.083842   257.005       27.3

![Hasil RFM Segmentation.png]()

* Segment Hibernating terdapat banyak pengguna yaitu 1066 (27%), diikuti segment Champion 550 (14.1%) dan segment Loyal Customers 546 (14.0%)

* Untuk segment Loyal Customers perlu dibuat program khusus yang fokus pada urgensi bertransaksi agar pengguna pada segment ini kembali bertransaksi dalam waktu dekat sehingga dapat naik ke segment Champion

* Untuk segment Potential Loyalists perlu dibuat program khusus yang fokus pada jumlah transaksi agar pengguna pada segment ini lebih sering melakukan transaksi sehingga dapat naik ke segmen Champion

* Untuk segment Hibernating perlu dibuat program khusus agar pengguna pada segment ini kembali bertransaksi sehingga bisa naik ke segment New Customers atau bahkan Potential Loyalistis